CREATE TABLE IF NOT EXISTS `form_gyn_physical` (
  `id`                  bigint(20)   NOT NULL auto_increment,
  `date`                datetime     DEFAULT NULL,
  `pid`                 bigint(20)   NOT NULL DEFAULT 0,
  `user`                varchar(255) DEFAULT NULL,
  `groupname`           varchar(255) DEFAULT NULL,
  `authorized`          tinyint(4)   NOT NULL DEFAULT 0,
  `activity`            tinyint(4)   NOT NULL DEFAULT 0,
`fld_1` varchar(3) NOT NULL default '--',
`fld_1_textbox` varchar(255) NOT NULL default '',
`fld_12` varchar(3) NOT NULL default '--',
`fld_12_textbox` varchar(255) NOT NULL default '',
`fld_17` varchar(3) NOT NULL default '--',
`fld_17_textbox` varchar(255) NOT NULL default '',
`fld_24` varchar(3) NOT NULL default '--',
`fld_24_textbox` varchar(255) NOT NULL default '',
`fld_25` varchar(3) NOT NULL default '--',
`fld_25_textbox` varchar(255) NOT NULL default '',
`fld_26` varchar(3) NOT NULL default '--',
`fld_26_textbox` varchar(255) NOT NULL default '',
`fld_27` varchar(3) NOT NULL default '--',
`fld_27_textbox` varchar(255) NOT NULL default '',
`fld_28` varchar(3) NOT NULL default '--',
`fld_28_textbox` varchar(255) NOT NULL default '',
`fld_29` varchar(3) NOT NULL default '--',
`fld_29_textbox` varchar(255) NOT NULL default '',
`fld_30` varchar(3) NOT NULL default '--',
`fld_30_textbox` varchar(255) NOT NULL default '',
`fld_34` varchar(3) NOT NULL default '--',
`fld_34_textbox` varchar(255) NOT NULL default '',
`fld_35` varchar(3) NOT NULL default '--',
`fld_35_textbox` varchar(255) NOT NULL default '',
`fld_36` varchar(3) NOT NULL default '--',
`fld_36_textbox` varchar(255) NOT NULL default '',
`fld_37` varchar(3) NOT NULL default '--',
`fld_37_textbox` varchar(255) NOT NULL default '',
`fld_38` varchar(3) NOT NULL default '--',
`fld_38_textbox` varchar(255) NOT NULL default '',
`fld_39` varchar(3) NOT NULL default '--',
`fld_39_textbox` varchar(255) NOT NULL default '',
`fld_40` varchar(3) NOT NULL default '--',
`fld_40_textbox` varchar(255) NOT NULL default '',
  PRIMARY KEY (id)
) TYPE=InnoDB;
